### ISSUE TITLE
Many issues, not working out of the box

### ISSUE THREAD

**Issue by ghost** [sbcshop/PiFan#1]
File "main.py", line 96, in <module>
    info_print()
  File "main.py", line 45, in info_print
    display = SSD1306()
  File "/home/pi/PiFan/oled_091.py", line 87, in __init__
    i2c_interface.__init__(self, address=address)
  File "/home/pi/PiFan/oled_091.py", line 52, in __init__
    self.bus = SMBus(self.bus_id())
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function i2c_interface.__del__ at 0x7623f270>
Traceback (most recent call last):
  File "/home/pi/PiFan/oled_091.py", line 56, in __del__
    self.close_i2c()
  File "/home/pi/PiFan/oled_091.py", line 59, in close_i2c
    self.bus.close()
AttributeError: 'SSD1306' object has no attribute 'bus'

**Comment by sbcshop** [comment]
Hi DieterUcll,

Please enable i2c interface first, You can use the Desktop GUI by heading to the Pi Start Menu > Preferences > Raspberry Pi Configuration > interface tab then enable i2c. restart your raspberry pi then try again.
